# Vaja
Za matriko 
$$ A=
\begin{bmatrix}
−1 & 1 & 1 & −1\\
1 & −1 & −1 &  1\\
2 & −2 & 2 & −2
\end{bmatrix}
$$
poišči poslošeni inverz (matriko $G$, za katero je $AGA=A$).

## Rešitev
1. izračunamo rang matrike $A$. 
2. v $A$ poiščemo neizrojeno $r\times r$ podmatriko $M$
3. v $A$ nadomestimo $M$ z $(M^{-1})^T$
4. vse ostale elemente v $A$ postavimo na $0$
5. dobljeno matriko transponiramo

In [1]:
A=[-1 1 1 -1; 1 -1 -1 1; 2 -2 2 -2];
% poiščemo rang in neizrojeno podmatriko
rref(A)

ans =

   1  -1   0   0
   0   0   1  -1
   0   0   0   0



In [6]:
% neizrojena podmatrika
im = [1,3];
in = [1,3];
det(A(im,in))

ans = -4


In [9]:
G = zeros(size(A));
G(im,in) = inv(A(im,in))';
G = G'

G =

  -0.50000   0.00000   0.25000
   0.00000   0.00000   0.00000
   0.50000   0.00000   0.25000
   0.00000   0.00000   0.00000



In [10]:
% preverimo, da je G res posplošeni inverz
A*G*A

ans =

  -1   1   1  -1
   1  -1  -1   1
   2  -2   2  -2



##Vaja 2. del
Ali je sistem $Ax=b$ rešljiv za 
$b=[0, 4, -4]$? Če ni, poišči projekcijo $b'$ vektorja $b$ na stolpčni prostor $C(A)$ in zapiši vse rešitve sistema $Ax=b'$.
##Rešitev

Projekcijo na podprostor lahko izračunamo s pomočjo normalnega sistema. To deluje le, če je matrika $A$ polnega ranga. V našem primeru je rang enak $2$, zato namesto cele matrike $A$ vzamemo podmatriko $B$ ranga $2$. Ker želimo projecirati na stolpčni prostor $C(A)$, za stolpce nove matrike uporabimo bazo $C(A)$, torej dva linearno neodvisna stolpca $A$. 
1. Projekcija $b'$ mora biti element $C(A)=C(B)$, zato jo lahko zapišemo kot $b'=Bx$
2. ker je projekcija pravokotna, mora biti razlika $b-b'\perp C(B)$, kar pomeni, da je $B^T(b-b')=0$.
3. iz enačbe $B^T(b-b')=B^T(b-Bx)=0$ izpeljemo normalni sistem
$$B^TBx=B^Tb$$
4. Projekcija $b'=Bx$, kjer je $x$ rešitev normalnega sistema. 

In [12]:
b=[0;4;-4];
% izberemo dva stolpca, ki sta linearno neodvisna
B=A(:,[1,3])

B =

  -1   1
   1  -1
   2   2



In [13]:
% rešimo normalni sistem in poiščemo projekcijo
x = (B'*B)\(B'*b);
b1 = B*x

b1 =

  -2
   2
  -4



Vse rešitve sistema $Ax=b'$ lahko dobimo s poslošenim inverzom $G$ kot
$$ x = Gb'+ (GA - I)z$$
kjer je $z$ poljuben $z\in\mathbb{R}^4$. Dimenzija množice rešitev je enaka dimenziji stolpčnega prostora matrike $GA-I$.

In [15]:
G*A-eye(4)

ans =

   0  -1   0   0
   0  -1   0   0
   0   0   0  -1
   0   0   0  -1



In [16]:
G*b1

ans =

   0
   0
  -2
   0



Rešitve sistema lahko zapišemo v parametrični obliki
$$ x = \begin{bmatrix}\alpha \\ \alpha \\ -2+\beta\\ \beta \end{bmatrix}$$ 

## Vaja 3. del
Poišči tisti vektor $x \in \mathbb{R}^4$, za katerega velja, da sta normi $\|Ax − b\|$ in $\|x\|$
najmanjši možni.
## Rešitev
Norma $\|Ax-b\|$ bo minimalna za vse rešitve sistme $Ax=b'$, zato moramo poiskati vektor $x$ oblike $x=[\alpha,\alpha,-2+\beta,\beta]^T$ z najmanjšo normo. Norma $\|x\|$ je funkcija parametrov $\alpha$ in $\beta$
$$\|x\|^2 = \alpha^2+\alpha^2+(\beta-2)^2+\beta^2.$$
Za minimum
1. je očitno $\alpha=0$ 
2. in $(\beta-2)^2+\beta^2$ minimalen.
 * minimum je v stacionarni točki: $2(\beta-2)+2\beta=4\beta-4=0$
 * in $\beta=1$

Rešitev je ena sama in sicer vektor $$x=\begin{bmatrix}0\\ 0\\ -1\\ 1\end{bmatrix}.$$